# Generated by Django 4.1 on 2022-09-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_product_description_product_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
